In [1]:
# Dependencies 
import pandas as pd
import numpy as np

In [3]:
#1. Loading dataset
wines_df = pd.read_csv('red_white.csv')
wines_df.head(20)

,wine_type,winetype_numeric,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,red,1,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
1,red,1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8
2,red,1,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8
3,red,1,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8
4,red,1,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
5,red,1,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4
6,red,1,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4
7,red,1,7.3,0.650,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0
8,red,1,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5
9,red,1,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5
10,red,1,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2
11,red,1,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5
12,red,1,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.9943,3.58,0.52,9.9
13,red,1,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.9974,3.26,1.56,9.1
14,red,1,8.9,0.620,0.18,3.8,0.176,52.0,145.0,0.9986,3.16,0.88,9.2
15,red,1,8.9,0.620,0.19,3.9,0.170,51.0,148.0,0.9986,3.17,0.93,9.2
16,red,1,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.9969,3.30,0.75,10.5
17,red,1,8.1,0.560,0.28,1.7,0.368,16.0,56.0,0.9968,3.11,1.28,9.3
18,red,1,7.4,0.590,0.08,4.4,0.086,6.0,29.0,0.9974,3.38,0.50,9.0
19,red,1,7.9,0.320,0.51,1.8,0.341,17.0,56.0,0.9969,3.04,1.08,9.2

In [6]:
#2. Info about the columns 
wines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2940 entries, 0 to 2939
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   wine_type             2940 non-null   object
 1   winetype_numeric      2940 non-null   int64
 2   fixed acidity         2940 non-null   float64
 3   volatile acidity      2940 non-null   float64
 4   citric acid           2940 non-null   float64
 5   residual sugar        2940 non-null   float64
 6   chlorides             2940 non-null   float64
 7   free sulfur dioxide   2940 non-null   float64
 8   total sulfur dioxide  2940 non-null   float64
 9   density               2940 non-null   float64
 10  pH                    2940 non-null   float64
 11  sulphates             2940 non-null   float64
 12  alcohol               2940 non-null   float64
dtypes: float64(11), int64(1), object(1)
memory usage: 298.7+ KB

In [ ]:
# if merging red and white datasets is needed in here, will do

In [7]:
#3. Count of RED wine instances
red_count = (wines_df["winetype_numeric"]==1).sum()

In [8]:
print (red_count)

1470

In [9]:
#4. Count of WHITE wine instances
white_count = (wines_df["winetype_numeric"]==2).sum()

In [10]:
print (white_count)

1470